project:
  type: website
  title: "vis_slides"
  output-dir: _site

execute:
  python: "/opt/conda/bin/python3"

format:
  revealjs:
      html-math-method:
      method: mathjax
      url: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    include-in-header: 
      - text: |
          <script src="https://cdn.plot.ly/plotly-2.35.2.min.js"></script>

website:
  sidebar:
    contents:
      - material/slides/vis_slides/DataVis-03-Techniques01.qmd
      - material/slides/vis_slides/DataVis-05-Techniques02.qmd
